# Generated by Django 2.0.7 on 2018-07-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Mapping to the GUI. Do not change unless you have to', max_length=255)),
                ('status', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, help_text='Determines how "filled" the centre will be in the GUI')),
            ],
        ),
        migrations.CreateModel(
            name='CentreDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.Centre')),
            ],
        ),
        migrations.CreateModel(
            name='CentreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.Centre')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AddField(
            model_name='centre',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.Company'),
        ),
    ]
