# Generated by Django 2.0.7 on 2018-07-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CentreDocument',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='CentreImage',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='centre',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='centres.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
