# Generated by Django 2.0.7 on 2018-07-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0004_auto_20180713_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='centres.Centre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='centres.Company'),
        ),
        migrations.AlterField(
            model_name='image',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='centres.Centre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='centres.Company'),
        ),
    ]
