# Generated by Django 2.0.7 on 2018-07-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0005_auto_20180713_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='text',
            new_name='description',
        ),
    ]
