# Generated by Django 3.0 on 2019-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0011_auto_20181129_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='centre',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='centres.Tag'),
        ),
    ]
