# Generated by Django 3.0 on 2019-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0013_auto_20191208_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
