# Generated by Django 3.0 on 2019-12-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0014_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalowner',
            name='name',
        ),
        migrations.AddField(
            model_name='historicalowner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centres.Company'),
        ),
    ]
