# Generated by Django 3.0 on 2020-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0016_auto_20200308_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='centre',
            name='sold_decade',
            field=models.CharField(blank=True, choices=[('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990'), ('2000', '2000'), ('2010', '2010'), ('2020', '2020')], max_length=4, null=True),
        ),
    ]
