# Generated by Django 3.0 on 2020-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0017_auto_20201022_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='sold_decade',
            new_name='sold',
        ),
        migrations.AddField(
            model_name='centre',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
    ]
