# Generated by Django 3.0 on 2020-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0018_auto_20201022_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
