# Generated by Django 3.0 on 2020-10-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0019_centre_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='public',
            new_name='private',
        ),
    ]
