# Generated by Django 3.0 on 2020-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0020_auto_20201030_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AddField(
            model_name='detailplan',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
    ]
