# Generated by Django 3.0 on 2020-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0021_auto_20201103_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='ownership_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='centre',
            name='ownership_description_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='centre',
            name='sold',
            field=models.CharField(blank=True, choices=[('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990'), ('2000', '2000'), ('2010', '2010'), ('2020', '2020'), ('0', 'Ongoing sale')], max_length=4, null=True),
        ),
    ]
