# Generated by Django 3.0 on 2020-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0022_auto_20201116_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='private',
        ),
        migrations.AddField(
            model_name='centre',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private'), ('none', 'none')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='ownership_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='centre',
            name='ownership_description_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
