# Generated by Django 3.0 on 2020-11-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0023_auto_20201116_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Publicly owned', 'Publicly owned'), ('Privately owned', 'Privately owned'), ('none', 'none')], default='none', max_length=255, null=True),
        ),
    ]
