export const actionTypes = {
  FETCH_STATION: '@@station/FETCH',
  STATION_FETCHED: '@@station/FETCHED',
  STATION_FETCH_FAILED: '@@station/FETCH_FAILED',

  COMPANY_DETAILS_FETCHED: '@@company_details/FETCHED',
  COMPANY_DETAILS_FETCH_FAILED: '@@company_details/FETCH_FAILED',

  COMPANIES_FETCHED: '@@company_details/COMPANIES_FETCHED',
  COMPANIES_FETCHED_FAILED: '@@company_details/COMPANIES_FETCHED_FAILED',

  OWNERSHIP_HISTORY_FETCHED: '@@ownership_history/FETCHED',
  OWNERSHIP_HISTORY_FETCHED_FAILED: '@@ownership_history/FETCH_FAILED',

  DOCUMENTS_FETCHED: '@@DOCUMENTS_FETCHED',
  DOCUMENTS_FETCHED_FAILED: '@@DOCUMENTS_FETCHED_FAILED',

  CURRENT_NODE_CHANGED: '@@current_node/CURRENT_NODE_CHANGED',

  MAP_CLICKED: '@@map/MAP_CLICKED',
  MAP_MOUSE_DOWN: '@@map/MAP_MOUSE_DOWN',
  MAP_MOUSE_UP: '@@map/MAP_MOUSE_UP',
  MAP_MOUSE_MOVE: '@@map/MAP_MOUSE_MOVE',

  MAP_DATA_FETCHED: '@@mapdata/FETCHED',
  MAP_DATA_FETCH_FAILED: '@@mapdata/FETCH_FAILED',

  TAG_DATA_FETCHED: '@@tagdata/FETCHED',
  TAG_DATA_FETCH_FAILED: '@@tagdata/FETCH_FAILED',

  SOLD_DATA_FETCHED: '@@solddata/FETCHED',
  SOLD_DATA_FETCH_FAILED: '@@solddata/FETCH_FAILED',

  TOGGLE_TAG_VISIBILITY: '@@map/TOGGLE_TAG_VISIBLE',
  TOGGLE_OWNER_VISIBILITY: '@@map/TOGGLE_OWNER_VISIBILITY',
  TOGGLE_SOLD_YEAR_VISIBILITY: '@@map/TOGGLE_SOLD_YEAR_VISIBILITY',
  TOGGLE_PUBLIC_VISIBILITY: '@@map/TOGGLE_PUBLIC_VISIBILITY',

  TOGGLE_FILTER_BOX_OPEN: '@@map/TOGGLE_FILTER_BOX_OPEN',
};
