# Generated by Django 2.0.2 on 2018-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.AddField(
            model_name='centredocument',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='centers.CentreImage'),
        ),
    ]
