# Generated by Django 2.0.2 on 2018-02-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20180228_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centredocument',
            name='images',
        ),
        migrations.AddField(
            model_name='centreimage',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.Centre'),
        ),
    ]
