# Generated by Django 2.0.2 on 2018-02-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20180228_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='documents',
        ),
        migrations.AddField(
            model_name='centre',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='centredocument',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.Centre'),
        ),
    ]
