# Generated by Django 2.0.2 on 2018-02-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_auto_20180228_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='key',
        ),
        migrations.AddField(
            model_name='centre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='centre',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
